name: validate-lab-2
on:
  push:
    branches:
      - master
    paths:
      - "lab-2/**"
  workflow_dispatch:
jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_notification_email: ${{ secrets.NOTIFICATION_EMAIL }}
    defaults:
      run:
        working-directory: lab2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: "1.7.5"
      - name: Import Public Key
        run: mkdir -p ~/.ssh && echo '${{ secrets.SSH_PUBLIC_KEY }}' > ~/.ssh/id_rsa.pub

      - name: Terraform Init, Validate, Format
        run: |
          terraform init
          terraform validate
          terraform fmt -check
